apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ar3q8bqi6-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ar3q8bqi6-java-quarkus-gitops